language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    packages:
    - libmysqlclient-dev
    - libperl-dev
    - libboost-dev
    - liblua5.1-0-dev
    - zlib1g-dev
script:
  - cmake -G "Unix Makefiles" -DEQEMU_BUILD_TESTS=OFF
  - make
branches:
  only:
    - master
    - Dev
notifications:
  email: false
  irc:
    channels: "irc.eqemulator.net#takp-dev"
os: linux
